/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as OrchRouteImport } from './routes/_orch'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsOrchestratorRouteImport } from './routes/settings.orchestrator'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as OrchOrchIndexRouteImport } from './routes/_orch.orch.index'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as OrchOrchEnvironmentIdProjectIdRouteImport } from './routes/_orch.orch.$environmentId.$projectId'
import { Route as OrchOrchEnvironmentIdProjectIdTasksTaskIdRouteImport } from './routes/_orch.orch.$environmentId.$projectId_.tasks.$taskId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const OrchRoute = OrchRouteImport.update({
  id: '/_orch',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrchestratorRoute = SettingsOrchestratorRouteImport.update({
  id: '/orchestrator',
  path: '/orchestrator',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const OrchOrchIndexRoute = OrchOrchIndexRouteImport.update({
  id: '/orch/',
  path: '/orch/',
  getParentRoute: () => OrchRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const OrchOrchEnvironmentIdProjectIdRoute =
  OrchOrchEnvironmentIdProjectIdRouteImport.update({
    id: '/orch/$environmentId/$projectId',
    path: '/orch/$environmentId/$projectId',
    getParentRoute: () => OrchRoute,
  } as any)
const OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute =
  OrchOrchEnvironmentIdProjectIdTasksTaskIdRouteImport.update({
    id: '/orch/$environmentId/$projectId_/tasks/$taskId',
    path: '/orch/$environmentId/$projectId/tasks/$taskId',
    getParentRoute: () => OrchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/orchestrator': typeof SettingsOrchestratorRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/orch/': typeof OrchOrchIndexRoute
  '/orch/$environmentId/$projectId': typeof OrchOrchEnvironmentIdProjectIdRoute
  '/orch/$environmentId/$projectId/tasks/$taskId': typeof OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/orchestrator': typeof SettingsOrchestratorRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/orch': typeof OrchOrchIndexRoute
  '/orch/$environmentId/$projectId': typeof OrchOrchEnvironmentIdProjectIdRoute
  '/orch/$environmentId/$projectId/tasks/$taskId': typeof OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/_orch': typeof OrchRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/orchestrator': typeof SettingsOrchestratorRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_orch/orch/': typeof OrchOrchIndexRoute
  '/_orch/orch/$environmentId/$projectId': typeof OrchOrchEnvironmentIdProjectIdRoute
  '/_orch/orch/$environmentId/$projectId_/tasks/$taskId': typeof OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/orchestrator'
    | '/settings/providers'
    | '/settings/source-control'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/orch/'
    | '/orch/$environmentId/$projectId'
    | '/orch/$environmentId/$projectId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/orchestrator'
    | '/settings/providers'
    | '/settings/source-control'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/orch'
    | '/orch/$environmentId/$projectId'
    | '/orch/$environmentId/$projectId/tasks/$taskId'
  id:
    | '__root__'
    | '/_chat'
    | '/_orch'
    | '/pair'
    | '/settings'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/orchestrator'
    | '/settings/providers'
    | '/settings/source-control'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/_orch/orch/'
    | '/_orch/orch/$environmentId/$projectId'
    | '/_orch/orch/$environmentId/$projectId_/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  OrchRoute: typeof OrchRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_orch': {
      id: '/_orch'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OrchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/orchestrator': {
      id: '/settings/orchestrator'
      path: '/orchestrator'
      fullPath: '/settings/orchestrator'
      preLoaderRoute: typeof SettingsOrchestratorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_orch/orch/': {
      id: '/_orch/orch/'
      path: '/orch'
      fullPath: '/orch/'
      preLoaderRoute: typeof OrchOrchIndexRouteImport
      parentRoute: typeof OrchRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_orch/orch/$environmentId/$projectId': {
      id: '/_orch/orch/$environmentId/$projectId'
      path: '/orch/$environmentId/$projectId'
      fullPath: '/orch/$environmentId/$projectId'
      preLoaderRoute: typeof OrchOrchEnvironmentIdProjectIdRouteImport
      parentRoute: typeof OrchRoute
    }
    '/_orch/orch/$environmentId/$projectId_/tasks/$taskId': {
      id: '/_orch/orch/$environmentId/$projectId_/tasks/$taskId'
      path: '/orch/$environmentId/$projectId/tasks/$taskId'
      fullPath: '/orch/$environmentId/$projectId/tasks/$taskId'
      preLoaderRoute: typeof OrchOrchEnvironmentIdProjectIdTasksTaskIdRouteImport
      parentRoute: typeof OrchRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface OrchRouteChildren {
  OrchOrchIndexRoute: typeof OrchOrchIndexRoute
  OrchOrchEnvironmentIdProjectIdRoute: typeof OrchOrchEnvironmentIdProjectIdRoute
  OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute: typeof OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute
}

const OrchRouteChildren: OrchRouteChildren = {
  OrchOrchIndexRoute: OrchOrchIndexRoute,
  OrchOrchEnvironmentIdProjectIdRoute: OrchOrchEnvironmentIdProjectIdRoute,
  OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute:
    OrchOrchEnvironmentIdProjectIdTasksTaskIdRoute,
}

const OrchRouteWithChildren = OrchRoute._addFileChildren(OrchRouteChildren)

interface SettingsRouteChildren {
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsOrchestratorRoute: typeof SettingsOrchestratorRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsOrchestratorRoute: SettingsOrchestratorRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  OrchRoute: OrchRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
